movies=[
    {
        id:1,
        name:"War",
        rating:"7.8/10",
        votes:"71.5K",
        city:["Delhi","Mumbai", "Ahmedabad","Banglore", "Chennai","Kolkata","Chandigarh"],
        language:["Hindi","English"],
        format:["2D","3D","4DX","IMAX 2D",],
        genre:["Action"],
        img:"http://www.deucreatives.com/wp-content/uploads/2019/09/70655693_10157828111134407_6781510359724326912_n.jpg",
        coverImg:"https://c.ndtvimg.com/2019-10/2uuqsfpg_war-movie-review_625x300_02_October_19.jpg",
        about:"War is an intense armed conflict between states, governments, societies, or paramilitary groups such as mercenaries, insurgents, and militias. It is generally characterized by extreme violence, destruction, and mortality, using regular or irregular military forces.",
        releasing:"24 Aug, 2019",
        time:"2h 36m",
        cast:["Hrithik Roshan","Tiger Shroff","Vaani Kapoor","Anupriya Goenka"]
    },
    {
        id:2,
        name:"Sooryavanshi",
        rating:"8.2/10",
        votes:"89.2K",
        city:["Delhi","Kolkata", "Ahmedabad", "Banglore", "Chennai", "Mumbai"],
        language:["Hindi","English","Panjabi","Gujarati"],
        format:["2D","3D"],
        genre:["Action","Comedy","Drama"],
        img:"https://image.songsuno.com/movie-images/original/movie/sooryavanshi-(2020)/sooryavanshi-(2020)-poster.jpg",
        coverImg:"https://www.bollywoodhungama.com/wp-content/uploads/2018/12/Sooryavanshi-banner.jpg",
        about:"Sooryavanshi: During the 1993 Mumbai blasts, Veer Surya Sooryavanshi loses his parents where he becomes motivated to become an ATS officer. Years later, Bilal Ahmed, the blasts' mastermind seeks refuge with dreaded terrorist Omar Hafeez at POK, as they begin planning more such attacks.",
        releasing:"5 Nov, 2021",
        time:"2h 25m",
        cast:["Akshay Kumar","Niharica Raizada","Katrina Kaif","Ajay Devgn","Ranveer Singh"],
    },
    {
        id:3,
        name:"KGF",
        rating:"9.5/10",
        votes:"42.5K",
        city:["Delhi", "Ahmedabad", "Banglore", "Chennai", "Mumbai","Chandigarh","Kolkata","Hyderabad"],
        language:["Hindi","English","Tamil","Panjabi","Telugu","Gujarati"],
        format:["2D","3D","IMAX 2D","MX4D","2D SCREEN X"],
        genre:["Action","Drama"],
        img:"https://mir-s3-cdn-cf.behance.net/project_modules/1400/1b739c74284099.5c2a29444cdef.png",
        coverImg:"https://th-i.thgim.com/public/todays-paper/tp-opinion/nvvgym/article65427951.ece/alternates/FREE_1200/19th-oped-film_%2BGD19QV6VC.4.jpg.jpg",
        about:"K.G.F is an Indian period action film series set mostly in the Kolar Gold Fields, which gives the series its name, created by Prashanth Neel and produced by Hombale Films starring Yash in lead role with an ensemble supporting cast.",
        releasing:"21 Dec, 2018",
        time:"2h 35m",
        cast:["Yash","Srinidhi","Anant Nag","Archana Jois","Achyuth Kumar"],
    
    },
    {
        id:4,
        name:"Hungama 2",
        rating:"5.2/10",
        votes:"3.2K",
        city:["Delhi", "Kolkata", "Banglore", "Chennai", "Mumbai"],
        language:["Hindi"],
        format:["2D"],
        genre:["Comedy","Romantic","Drama"],
        img:"https://img1.hotstarext.com/image/upload/f_auto,t_web_vl_2_5x/sources/r1/cms/prod/1535/1101535-v-cac451b9ee92",
        coverImg:"https://i.ytimg.com/vi/RC8dHEENNHQ/maxresdefault.jpg",
        about:"Hungama 2 is a 2021 Indian Hindi-language romantic comedy film directed by Priyadarshan and jointly produced by Ratan Jain, Ganesh Jain, Chetan Jain and Armaan Ventures. It is the spiritual sequel of Priyadarshan's own 2003 film Hungama. It is loosely based on Priyadarshan's own 1994 Malayalam film Minnaram with a comedy sequence borrowed from his other Malayalam film Vandanam (1989) both starring Mohanlal.",
        releasing:"23 Jul, 2021",
        time:"2h 36m",
        cast:["Pranitha Subhash","Meezaan Jafri","Shilpa Shetty","Naira Shah"],
    
    },
    {
        id:5,
        name:"1920",
        rating:"6.1/10",
        votes:"4.7K",
        city:["Delhi", "Kolkata", "Banglore",,"Pune","Chennai", "Mumbai","Chandigarh"],
        language:["Hindi","Tamil","Panjabi"],
        format:["2D","3D"],
        genre:["Horror"],
        img:"https://assets-in.bmscdn.com/iedb/movies/images/mobile/thumbnail/xlarge/1920-london-et00040613-08-10-2016-03-17-14.jpg",
        coverImg:"https://assets-in.bmscdn.com/iedb/movies/images/mobile/listing/medium/1920-horrors-of-the-heart-et00353537-1687330964.jpg",
        about:"1920: Filmed in Hindi, the plot revolves around the events surrounding a married couple living in a haunted house in the year 1920. The film stars debutant actors Rajneesh Duggal and Adah Sharma as the married couple, along with Indraneil Sengupta in a special role.",
        releasing:"12 Sep, 2018",
        time:"2h 3m",
        cast:["Avika Gor","Barkha Bisht","Ketaki Kulkarni","Danish Pandor"],
    },
    {
        id:6,
        name:"Shiddat",
        rating:"7.2/10",
        votes:"6.1K",
        city:["Delhi", "Kolkata", "Hyderabad","Ahmedabad","Pune","Chennai", "Mumbai","Chandigarh"],
        language:["Hindi","Panjabi","Gujarati","Tamil","Marathi"],
        format:["2D","3D","4DX","IMAX 2D"],
        genre:["Romantic","Drama"],
        img:"https://m.media-amazon.com/images/M/MV5BYWRmYWY3NGItYjY5OC00YTAwLWE2ODMtODJjOTQ3YWFhNDg4XkEyXkFqcGdeQXVyMTI1NDEyNTM5._V1_.jpg",
        coverImg:"https://i.ytimg.com/vi/RES6xGcI7So/maxresdefault.jpg",
        about:"Shiddat: Journey Beyond Love, or simply Shiddat ( transl. Passion), is a 2021 Indian Hindi-language romantic drama film directed by Kunal Deshmukh and produced by Bhushan Kumar, Krishan Kumar and Dinesh Vijan under their banners T-Series and Maddock Films.",
        releasing:"1 Oct, 2021",
        time:"2h 36m",
        cast:["Radhika Madan","Sunny Kaushal","Diana Penty","Mohit Raina"],
    },
    {
        id:7,
        name:"Ghost",
        rating:"7.1/10",
        votes:"5.5K",
        city:["Delhi", "Kolkata", "Banglore",,"Pune","Chennai", "Mumbai","Chandigarh"],
        language:["Hindi","Panjabi","Gujarati"],
        format:["2D","3D","IMAX 2D"],
        genre:["Horror"],
        img:"https://upload.wikimedia.org/wikipedia/en/b/ba/Ghost_Film_Poster.jpg",
        coverImg:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTnzHNw3D8W5-Vf7Vn3pObyRQjPfOFrfUhINA&usqp=CAU",
        about:"Ghost: After a young man is murdered, his spirit stays behind to warn his lover of impending danger, with the help of a reluctant psychic. After a young man is murdered, his spirit stays behind to warn his lover of impending danger, with the help of a reluctant psychic.",
        releasing:"5 Oct, 2022",
        time:"2h 18m",
        cast:["Nagarjuna","Vikram Naidu","Anikha Surendran","Sonal Chauhan"],
    },

    {
        id:8,
        name:"HIT: The Second Case",
        rating:"7.8/10",
        votes:"6.2K",
        city:["Delhi", "Kolkata", "Banglore","Hyderabad","Pune","Chennai", "Mumbai","Chandigarh","Ahmedabad"],
        language:["Hindi","Gujarati","Tamil","Telugu","Malayalam"],
        format:["2D","3D","IMAX 2D"],
        genre:["Crime"],
        img:"https://m.media-amazon.com/images/M/MV5BOGJmMmRmN2UtYjI2MS00OGEyLTk0MzAtNjc4Yzc2ZjdmODI4XkEyXkFqcGdeQXVyMTA3MDk2NDg2._V1_.jpg",
        coverImg:"https://www.bollymoviereviewz.com/wp-content/uploads/2022/12/Hit-2-Movie-Review-1.jpg",
        about:"HIT: The Second Case: It is the second installment in the HITverse following HIT: The First Case (2020). The film stars Adivi Sesh, Meenakshi Chaudhary and Rao Ramesh. The plot follows Krishna Dev (Sesh) solving a serial murder case in Visakhapatnam.",
        releasing:"2 Dec, 2022",
        time:"1h 58m",
        cast:["Meenakshi Chaudhary","Adivi Sesh","Arjun Sarkaar","Komalee Prasad"],
    },
    {
        id:9,
        name:"Inception",
        rating:"8.1/10",
        votes:"2.6K",
        city:["Delhi", "Kolkata", "Banglore","Hyderabad","Pune","Chennai", "Mumbai","Chandigarh","Ahmedabad"],
        language:["English","Hindi","Gujarati","Tamil"],
        format:["2D","3D","MX4D"],
        genre:["Action","Adventure","Crime"],
        img:"https://www.tallengestore.com/cdn/shop/products/Inception-LeonardoDiCaprio-ChristopherNolan-HollywoodSciFiMoviePoster_b053c9c0-e1d8-4021-951e-ccce86bea015.jpg?v=1685582038",
        coverImg:"https://images.squarespace-cdn.com/content/v1/5ec686197f8b2976074846c2/1618809593080-N5PB8CWYOW3OPDE2TT6E/Feature+3-1.png?format=1000w",
        about:"Inception: Dom Cobb (Leonardo DiCaprio) is a thief with the rare ability to enter people's dreams and steal their secrets from their subconscious. His skill has made him a hot commodity in the world of corporate espionage but has also cost him everything he loves.",
        releasing:"16 Jul, 2010",
        time:"2h 28m",
        cast:["Leonardo DiCaprio","Joseph Gordon","Cillian Murphy","Tom Hardy"],
    },
    {
        id:10,
        name:"Into the Woods",
        rating:"5.9/10",
        votes:"1.8K",
        city:["Delhi","Hyderabad","Pune","Chennai", "Mumbai","Chandigarh","Ahmedabad"],
        language:["English","Hindi","Gujarati","Tamil","Malayalam"],
        format:["2D","3D","4DX","IMAX 2D","MX4D"],
        genre:["Musical"],
        img:"https://lumiere-a.akamaihd.net/v1/images/p_intothewoods_19906_d3b548e1.jpeg",
        coverImg:"https://images-na.ssl-images-amazon.com/images/S/pv-target-images/146ae8dc412a14ac3d4e0a7fd3f54aa6f3eea554740e1eaaaf5081891e164f6d._RI_V_TTW_.jpg",
        about:"Into the Woods: A Baker and his wife live in a village where they all wish for something they can't have. The Baker and his Wife wish for a child, but they soon find out that because of a family curse they can't have any children until they find multiple things for the witch that cursed them in the first place.",
        releasing:"25 Dec, 2016",
        time:"2h 5m",
        cast:["Meryl Streep","Emily Blunt","Anna Kendrick","James Corden"],
    },
    {
        id:11,
        name:"Ramayana",
        rating:"6.4/10",
        votes:"3.5K",
        city:["Delhi","Hyderabad","Pune","Chennai", "Mumbai","Chandigarh","Ahmedabad"],
        language:["Hindi"],
        format:["2D"],
        genre:["Adventure","Animation"],
        img:"https://m.media-amazon.com/images/M/MV5BNjcwNDUzNTUtYzcwNy00NWEyLWFhNGMtMTY1Nzg4YjVkN2UxXkEyXkFqcGdeQXVyODE5NzE3OTE@._V1_.jpg",
        coverImg:"https://www.famousbollywood.com/wp-content/uploads/2023/06/ramayana-.webp",
        about:"Ramayana: The Epic is a 2010 Indian Hindi-language computer-animated mythological action film from Maya Digital Media. Directed by Chetan Desai and produced by Ketan Mehta, it was released by Warner Bros. India on 15 October 2010.Based on the Valmiki's Ramayana, this film explores the FUSION style of animation that consists of three different schools of animation-Manga from Japan, Disney from the US and Ravi Varma from India.",
        releasing:"25 Aug, 2019",
        time:"2h 15m",
        cast:["Arun Govil","Bryan Cranston","Amrish Puri","Uday Mathan"],
    },
    {
        id:12,
        name:"Peter Pan & Wendy",
        rating:"5.7/10",
        votes:"3.2K",
        city:["Delhi","Hyderabad","Pune","Chennai", "Mumbai","Chandigarh","Ahmedabad","Hyderabad"],
        language:["English","Hindi","Gujarati","Tamil","Malayalam","Korean"],
        format:["2D","3D","IMAX 2D","ICE"],
        genre:["Family","Animation"],
        img:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRsE0LTmw4g0LwfoXaCavF28Wtlj1mUwG9mrkE8TOc8TgUwSzV7mdPw6ec-rPg_VHpn1zI&usqp=CAU",
        coverImg:"https://prod-ripcut-delivery.disney-plus.net/v1/variant/disney/2CD89F6D3231FEBEA691F4581309820FDFC41E6C1B9B189952F6E597AF355C09/scale?width=1200&aspectRatio=1.78&format=jpeg",
        about:"Peter Pan & Wendy: The story follows Peter Pan and Wendy, who go to the magical world of Neverland with Wendy's brothers and Peter's best friend Tinker Bell. Along the way, Wendy embarks on the adventure that will change her life and encounters Peter's archenemy Captain Hook.",
        releasing:"5 Feb, 2023",
        time:"1h 49m",
        cast:["Ever Anderson","Alexander Molony","Captain Hook","Alyssa Wapanatâhk"],
    }

]

cities=[
    {name:"Delhi",img:"//in.bmscdn.com/m6/images/common-modules/regions/ncr.png",selectImg:"//in.bmscdn.com/m6/images/common-modules/regions/ncr-selected.png"},
    {name:"Mumbai",img:"//in.bmscdn.com/m6/images/common-modules/regions/mumbai.png",selectImg:"//in.bmscdn.com/m6/images/common-modules/regions/mumbai-selected.png"},
    {name:"Ahmedabad",img:"//in.bmscdn.com/m6/images/common-modules/regions/ahd.png",selectImg:"//in.bmscdn.com/m6/images/common-modules/regions/ahd-selected.png"},
    {name:"Hyderabad",img:"//in.bmscdn.com/m6/images/common-modules/regions/hyd.png",selectImg:"//in.bmscdn.com/m6/images/common-modules/regions/hyd-selected.png"},
    {name:"Banglore",img:"//in.bmscdn.com/m6/images/common-modules/regions/bang.png",selectImg:"//in.bmscdn.com/m6/images/common-modules/regions/bang-selected.png"},
    {name:"Chennai",img:"//in.bmscdn.com/m6/images/common-modules/regions/chen.png",selectImg:"//in.bmscdn.com/m6/images/common-modules/regions/chen-selected.png"},
    {name:"Pune",img:"//in.bmscdn.com/m6/images/common-modules/regions/pune.png",selectImg:"//in.bmscdn.com/m6/images/common-modules/regions/pune-selected.png"},
    {name:"Kolkata",img:"//in.bmscdn.com/m6/images/common-modules/regions/kolk.png",selectImg:"//in.bmscdn.com/m6/images/common-modules/regions/kolk-selected.png"},
    {name:"Chandigarh",img:"//in.bmscdn.com/m6/images/common-modules/regions/chd.png",selectImg:"//in.bmscdn.com/m6/images/common-modules/regions/chd-selected.png"},
],

users=[
    {id:1,email:"test@test.com",firstName:"Jane",lastName:"Doe",gender:"man",married:"No",mobileNo:9811574521,password:"test1234"},
]
module.exports= {movies,users,cities};