movies=[
    {
        id:1,
        name:"War",
        rating:"78%",
        votes:"264,871",
        city:["Delhi","Mumbai", "Ahmedabad","Banglore", "Chennai","Kolkata","Chandigarh"],
        language:["Hindi","English"],
        format:["2D","3D","4DX","IMAX 2D"],
        genre:["Action"],
        img:"http://www.deucreatives.com/wp-content/uploads/2019/09/70655693_10157828111134407_6781510359724326912_n.jpg",
        coverImg:"https://c.ndtvimg.com/2019-10/2uuqsfpg_war-movie-review_625x300_02_October_19.jpg",
    },
    {
        id:2,
        name:"Sooryavanshi",
        rating:"82%",
        votes:"321,258",
        city:["Kolkata", "Ahmedabad", "Banglore", "Chennai", "Mumbai"],
        language:["Hindi","English","Panjabi","Gujarati"],
        format:["2D","3D"],
        genre:["Action","Comedy"],
        img:"https://image.songsuno.com/movie-images/original/movie/sooryavanshi-(2020)/sooryavanshi-(2020)-poster.jpg",
        coverImg:"https://www.bollywoodhungama.com/wp-content/uploads/2018/12/Sooryavanshi-banner.jpg"
    },
    {
        id:3,
        name:"KGF",
        rating:"94%",
        votes:"401,278",
        city:["Delhi", "Ahmedabad", "Banglore", "Chennai", "Mumbai","Chandigarh","Kolkata"],
        language:["Hindi","English","Tamil","Panjabi","Telugu","Gujarati"],
        format:["2D","3D","4DX","IMAX 2D","MX4D","2D SCREEN X","ICE"],
        genre:["Action","Comedy","Romantic"],
        img:"https://mir-s3-cdn-cf.behance.net/project_modules/1400/1b739c74284099.5c2a29444cdef.png",
        coverImg:"https://th-i.thgim.com/public/todays-paper/tp-opinion/nvvgym/article65427951.ece/alternates/FREE_1200/19th-oped-film_%2BGD19QV6VC.4.jpg.jpg"
    },





    {
        id:4,
        name:"Hungama 2",
        rating:"54%",
        votes:"3089",
        city:["Delhi", "Kolkata", "Banglore", "Chennai", "Mumbai"],
        language:["Hindi","English","Tamil"],
        format:["2D","3D","IMAX 2D"],
        genre:["Comedy","Romantic","Drama"],
        img:"https://img1.hotstarext.com/image/upload/f_auto,t_web_vl_2_5x/sources/r1/cms/prod/1535/1101535-v-cac451b9ee92",
        coverImg:"https://i.ytimg.com/vi/RC8dHEENNHQ/maxresdefault.jpg"
    },
    
   
    
]

halls=[
    {
        id:1,
        name:"Cinepolis:DLF Place, Saket",
        price:[250,420],
        like:false,
        movie:["War","Sooryavanshi","KGF"],
        city:["NCR", "Ahmedabad", "Banglore", "Chennai", "Mumbai", "Hyderabad"],
        times:["9:00 AM","12:00 PM","1:15 PM","3:45 PM","10:20 PM","11:35 PM"],
        morning:["9:00 AM"],
        afternoon:["12:00 PM","1:15 PM","3:45 PM"], 
        evening:[],
        night:["10:20 PM","11:35 PM"],
        showSeat:[
            {
                time:[
                    {name:"A", seatNo:[{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:true},{b:false},{b:false},{b:false},{b:false},{b:true},{b:false},{b:false},{b:false},{b:true},{b:false},{b:true}]},
                    {name:"B", seatNo:[{b:true},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false}]},
                    {name:"C", seatNo:[{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:true},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:true},{b:false},{b:false},{b:false},{b:false},{b:false},{b:true},{b:false},{b:false}]},
                    {name:"D", seatNo:[{b:false},{b:false},{b:false},{b:false},{b:false},{b:true},{b:false},{b:false},{b:false},{b:false},{b:false},{b:true},{b:false},{b:false},{b:false},{b:false},{b:true},{b:false},{b:false},{b:false},{b:true},{b:false},{b:false},{b:false},{b:true}]},
                    {name:"E", seatNo:[{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false}]},
                    {name:"F", seatNo:[{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false}]},
                    {name:"G", seatNo:[{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false}]},
                    {name:"H", seatNo:[{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false}]},
                    {name:"I", seatNo:[{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false}]},
                    {name:"J", seatNo:[{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false}]},
                    {name:"K", seatNo:[{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false}]},
                    {name:"L", seatNo:[{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false}]},           
                    {name:"N", seatNo:[{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false}]},
                    {name:"O", seatNo:[{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false}]},
            ],
            },
            {
                time:[
                    {name:"A", seatNo:[{b:true},{b:true},{b:true},{b:true},{b:false},{b:false},{b:false},{b:true},{b:false},{b:true},{b:false},{b:false},{b:true},{b:false},{b:false},]},
                    {name:"B", seatNo:[{b:true},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false}]},
                    {name:"E", seatNo:[{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:true},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:true},{b:false},{b:false},{b:false},{b:false},{b:false},{b:true},{b:false},{b:false}]},
                    {name:"F", seatNo:[{b:false},{b:false},{b:false},{b:false},{b:false},{b:true},{b:false},{b:false},{b:false},{b:false},{b:false},{b:true},{b:false},{b:false},{b:false},{b:false},{b:true},{b:false},{b:false},{b:false},{b:true},{b:false},{b:false},{b:false},{b:true}]},
                    {name:"G", seatNo:[{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false}]},
                    {name:"H", seatNo:[{b:true},{b:false},{b:false},{b:false},{b:true},{b:false},{b:false},{b:false},{b:true},{b:false},{b:false},{b:true},{b:false},{b:false},{b:false},{b:true},{b:true},{b:false},{b:false},{b:false},{b:true},{b:true}]},
                    {name:"I", seatNo:[{b:false},{b:false},{b:false},{b:false},{b:true},{b:false},{b:true},{b:false},{b:true},{b:false},{b:false},{b:false},{b:false},{b:false},{b:true},{b:false},{b:false},{b:false},{b:true},{b:false},{b:false},{b:false}]},
                    {name:"J", seatNo:[{b:false},{b:true},{b:false},{b:false},{b:false},{b:true},{b:false},{b:false},{b:false},{b:false},{b:false},{b:true},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:true},{b:false},{b:false},{b:false}]},
                    {name:"K", seatNo:[{b:false},{b:false},{b:false},{b:true},{b:false},{b:false},{b:true},{b:false},{b:false},{b:false},{b:true},{b:false},{b:false},{b:false},{b:true},{b:false},{b:false},{b:false},{b:true},{b:false},{b:false},{b:false}]},
                    {name:"L", seatNo:[{b:true},{b:false},{b:false},{b:false},{b:true},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:true},{b:false},{b:false},{b:false},{b:true},{b:false},{b:false},{b:false},{b:true}]},
                    {name:"M", seatNo:[{b:true},{b:true},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:true},{b:false},{b:false},{b:false},{b:true},{b:false},{b:false},{b:false}]},
                    {name:"N", seatNo:[{b:true},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:true},{b:false},{b:false},{b:false},{b:false},{b:false},{b:true},{b:false},{b:false},{b:false},{b:false},{b:true},{b:false},{b:false},{b:false}]},
                    {name:"O", seatNo:[{b:true},{b:true},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false}]},
                ],
            },
            {
                time:[
                    {name:"F",seatNo:[{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:true},{b:false},{b:false},{b:false},{b:false},{b:true},{b:false},{b:false},{b:false},{b:true},{b:false},{b:true}]},
                    {name:"G",seatNo:[{b:true},{b:false},{b:true},{b:false},{b:false},{b:true},{b:true},{b:false},{b:true},{b:false},{b:false},{b:false},{b:true},{b:true},{b:false}]},
                    {name:"C",seatNo:[{b:false},{b:false},{b:true},{b:true},{b:false},{b:true},{b:false},{b:true},{b:false},{b:false},{b:true},{b:true},{b:true},{b:true},{b:false},{b:false},{b:true},{b:false},{b:true},{b:true},{b:false},{b:false}]},
                    {name:"D",seatNo:[{b:false},{b:false},{b:false},{b:true},{b:true},{b:true},{b:true},{b:false},{b:false},{b:false},{b:true},{b:true},{b:true},{b:false},{b:false},{b:false},{b:true},{b:false},{b:false},{b:false},{b:true},{b:false},{b:true}]},
                    {name:"E",seatNo:[{b:false},{b:false},{b:false},{b:true},{b:true},{b:true},{b:true},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false}]},
                    {name:"F",seatNo:[{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false}]},
                    {name:"G",seatNo:[{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false}]},
                    {name:"H",seatNo:[{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false}]},
                    {name:"I",seatNo:[{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false}]},
                    {name:"J",seatNo:[{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false}]},
                    {name:"K",seatNo:[{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false}]},
                    {name:"L",seatNo:[{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false}]},
                    {name:"M",seatNo:[{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false}]},
                    {name:"N",seatNo:[{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false}]},
                    {name:"O",seatNo:[{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false}]},
                ],
            },
            {
                time:[
                    {name:"P", seatNo:[{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false}]},
                    {name:"Q", seatNo:[{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false}]},
                    {name:"C", seatNo:[{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false}]},
                    {name:"D", seatNo:[{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false}]},
                    {name:"E", seatNo:[{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false}]},
                    {name:"F", seatNo:[{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false}]},
                    {name:"G", seatNo:[{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false}]},
                    {name:"H", seatNo:[{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false}]},
                    {name:"I", seatNo:[{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false}]},
                    {name:"J", seatNo:[{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false}]},
                    {name:"K", seatNo:[{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false}]},
                    {name:"L", seatNo:[{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false}]},
                    {name:"M", seatNo:[{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false}]},
                    {name:"N", seatNo:[{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false}]},
                    {name:"O", seatNo:[{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false}]},
                ],
            },
            {
                time:[
                    {name:"A", seatNo:[{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},]},
                    {name:"B", seatNo:[{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false}]},
                    {name:"E", seatNo:[{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false}]},
                    {name:"F", seatNo:[{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false}]},
                    {name:"G", seatNo:[{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false}]},
                    {name:"H", seatNo:[{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false}]},
                    {name:"I", seatNo:[{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false}]},
                    {name:"J", seatNo:[{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false}]},
                    {name:"K", seatNo:[{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false}]},
                    {name:"L", seatNo:[{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false}]},
                    {name:"M", seatNo:[{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false}]},
                    {name:"N", seatNo:[{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false}]},
                    {name:"O", seatNo:[{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false}]},
                ],
            },
            {
                time:[
                    {name:"A", seatNo:[{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},]},
                    {name:"B", seatNo:[{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false}]},
                    {name:"E", seatNo:[{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false}]},
                    {name:"F", seatNo:[{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false}]},
                    {name:"G", seatNo:[{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false}]},
                    {name:"H", seatNo:[{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false}]},
                    {name:"I", seatNo:[{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false}]},
                    {name:"J", seatNo:[{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false}]},
                    {name:"K", seatNo:[{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false}]},
                    {name:"L", seatNo:[{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false}]},
                    {name:"M", seatNo:[{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false}]},
                    {name:"N", seatNo:[{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false}]},
                    {name:"O", seatNo:[{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false}]},
                ],
            },
        
        ]

        
    },
    {
        id:2,
        name:"Cinepolis: Cross River Mall, Shahdra",
        price:[150,250],
        like:false,
        movie:["War","Sooryavanshi","KGF"],
        city:["NCR","Banglore", "Chennai", "Mumbai", "Hyderabad"],
        times:["10:00 AM","2:00 PM","4:45 PM","6:00 PM","11:45 PM"],
        morning:["10:00 AM"],
        afternoon:["2:00 PM"], 
        evening:["4:45 PM","6:00 PM"],
        night:["11:45 PM"],
        showSeat:[
            {
                time:[
                    {name:"A", seatNo:[{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},]},
                    {name:"B", seatNo:[{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false}]},
                    {name:"E", seatNo:[{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false}]},
                    {name:"F", seatNo:[{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false}]},
                    {name:"G", seatNo:[{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false}]},
                    {name:"H", seatNo:[{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false}]},
                    {name:"I", seatNo:[{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false}]},
                    {name:"J", seatNo:[{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false}]},
                    {name:"K", seatNo:[{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false}]},
                    {name:"L", seatNo:[{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false}]},
                    {name:"M", seatNo:[{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false}]},
                    {name:"N", seatNo:[{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false}]},
                    {name:"O", seatNo:[{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false}]},
                ],
            },
            {
                time:[
                    {name:"A", seatNo:[{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},]},
                    {name:"B", seatNo:[{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false}]},
                    {name:"E", seatNo:[{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false}]},
                    {name:"F", seatNo:[{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false}]},
                    {name:"G", seatNo:[{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false}]},
                    {name:"H", seatNo:[{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false}]},
                    {name:"I", seatNo:[{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false}]},
                    {name:"J", seatNo:[{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false}]},
                    {name:"K", seatNo:[{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false}]},
                    {name:"L", seatNo:[{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false}]},
                    {name:"M", seatNo:[{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false}]},
                    {name:"N", seatNo:[{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false}]},
                    {name:"O", seatNo:[{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false}]},
                ],
            },
            {
                time:[
                    {name:"A", seatNo:[{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},]},
                    {name:"B", seatNo:[{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false}]},
                    {name:"E", seatNo:[{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false}]},
                    {name:"F", seatNo:[{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false}]},
                    {name:"G", seatNo:[{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false}]},
                    {name:"H", seatNo:[{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false}]},
                    {name:"I", seatNo:[{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false}]},
                    {name:"J", seatNo:[{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false}]},
                    {name:"K", seatNo:[{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false}]},
                    {name:"L", seatNo:[{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false}]},
                    {name:"M", seatNo:[{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false}]},
                    {name:"N", seatNo:[{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false}]},
                    {name:"O", seatNo:[{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false}]},
                ],
            },
            {
                time:[
                    {name:"A", seatNo:[{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},]},
                    {name:"B", seatNo:[{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false}]},
                    {name:"E", seatNo:[{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false}]},
                    {name:"F", seatNo:[{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false}]},
                    {name:"G", seatNo:[{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false}]},
                    {name:"H", seatNo:[{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false}]},
                    {name:"I", seatNo:[{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false}]},
                    {name:"J", seatNo:[{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false}]},
                    {name:"K", seatNo:[{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false}]},
                    {name:"L", seatNo:[{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false}]},
                    {name:"M", seatNo:[{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false}]},
                    {name:"N", seatNo:[{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false}]},
                    {name:"O", seatNo:[{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false}]},
                ],
            },
            {
                time:[
                    {name:"A", seatNo:[{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},]},
                    {name:"B", seatNo:[{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false}]},
                    {name:"E", seatNo:[{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false}]},
                    {name:"F", seatNo:[{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false}]},
                    {name:"G", seatNo:[{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false}]},
                    {name:"H", seatNo:[{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false}]},
                    {name:"I", seatNo:[{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false}]},
                    {name:"J", seatNo:[{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false}]},
                    {name:"K", seatNo:[{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false}]},
                    {name:"L", seatNo:[{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false}]},
                    {name:"M", seatNo:[{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false}]},
                    {name:"N", seatNo:[{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false}]},
                    {name:"O", seatNo:[{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false}]},
                ],
            },
            
        ]
    },
    {
        id:3,
        name:"Carnival: TGIP",
        price:[99,320],
        like:false,
        movie:["War","Sooryavanshi","KGF"],
        city:["NCR", "Ahmedabad", "Banglore", "Chennai"],
        times:["1:15 PM","2:45 PM","3:05 PM","7:00 PM","9:50 PM"],
        morning:[],
        afternoon:["1:15 PM","2:45 PM"], 
        evening:["3:05 PM"],
        night:["7:00 PM","9:50 PM"],
        showSeat:[
            {
                time:[
                    {name:"A", seatNo:[{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},]},
                    {name:"B", seatNo:[{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false}]},
                    {name:"E", seatNo:[{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false}]},
                    {name:"F", seatNo:[{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false}]},
                    {name:"G", seatNo:[{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false}]},
                    {name:"H", seatNo:[{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false}]},
                    {name:"I", seatNo:[{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false}]},
                    {name:"J", seatNo:[{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false}]},
                    {name:"K", seatNo:[{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false}]},
                    {name:"L", seatNo:[{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false}]},
                    {name:"M", seatNo:[{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false}]},
                    {name:"N", seatNo:[{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false}]},
                    {name:"O", seatNo:[{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false}]},
                ],
            },
            {
                time:[
                    {name:"A", seatNo:[{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},]},
                    {name:"B", seatNo:[{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false}]},
                    {name:"E", seatNo:[{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false}]},
                    {name:"F", seatNo:[{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false}]},
                    {name:"G", seatNo:[{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false}]},
                    {name:"H", seatNo:[{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false}]},
                    {name:"I", seatNo:[{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false}]},
                    {name:"J", seatNo:[{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false}]},
                    {name:"K", seatNo:[{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false}]},
                    {name:"L", seatNo:[{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false}]},
                    {name:"M", seatNo:[{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false}]},
                    {name:"N", seatNo:[{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false}]},
                    {name:"O", seatNo:[{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false}]},
                ],
            },
            {
                time:[
                    {name:"A", seatNo:[{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},]},
                    {name:"B", seatNo:[{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false}]},
                    {name:"E", seatNo:[{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false}]},
                    {name:"F", seatNo:[{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false}]},
                    {name:"G", seatNo:[{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false}]},
                    {name:"H", seatNo:[{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false}]},
                    {name:"I", seatNo:[{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false}]},
                    {name:"J", seatNo:[{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false}]},
                    {name:"K", seatNo:[{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false}]},
                    {name:"L", seatNo:[{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false}]},
                    {name:"M", seatNo:[{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false}]},
                    {name:"N", seatNo:[{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false}]},
                    {name:"O", seatNo:[{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false}]},
                ],
            },
            {
                time:[
                    {name:"A", seatNo:[{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},]},
                    {name:"B", seatNo:[{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false}]},
                    {name:"E", seatNo:[{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false}]},
                    {name:"F", seatNo:[{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false}]},
                    {name:"G", seatNo:[{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false}]},
                    {name:"H", seatNo:[{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false}]},
                    {name:"I", seatNo:[{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false}]},
                    {name:"J", seatNo:[{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false}]},
                    {name:"K", seatNo:[{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false}]},
                    {name:"L", seatNo:[{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false}]},
                    {name:"M", seatNo:[{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false}]},
                    {name:"N", seatNo:[{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false}]},
                    {name:"O", seatNo:[{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false}]},
                ],
            },
            {
                time:[
                    {name:"A", seatNo:[{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},]},
                    {name:"B", seatNo:[{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false}]},
                    {name:"E", seatNo:[{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false}]},
                    {name:"F", seatNo:[{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false}]},
                    {name:"G", seatNo:[{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false}]},
                    {name:"H", seatNo:[{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false}]},
                    {name:"I", seatNo:[{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false}]},
                    {name:"J", seatNo:[{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false}]},
                    {name:"K", seatNo:[{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false}]},
                    {name:"L", seatNo:[{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false}]},
                    {name:"M", seatNo:[{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false}]},
                    {name:"N", seatNo:[{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false}]},
                    {name:"O", seatNo:[{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false},{b:false}]},
                ],
            },
            
            
        ]
        
    }

]
booksTicket=[
    {
        userId:1,
        tickets:[{ticketId:1,title:" War", movieHall: "Cinepolis: DLF Place, Saket", tickets: ["A1","B3"], amount: 420, time: "1:15 PM", date : "16 Jul" }]
    }
    
]
users=[
    {id:1,email:"test@test.com",firstName:"Jane",lastName:"Doe",married:"No",mobileNo:9811574521,password:"test1234"},
]
module.exports= {movies,halls,users,booksTicket};